---
- name: copy sssd.conf
  ansible.builtin.template:
    src: sssd.conf
    dest: "{{ sysconfdir }}/sssd/sssd.conf"
    mode: 0600

- name: enable sss_ssh_authorizedkeys
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?AuthorizedKeysCommand '
    line: AuthorizedKeysCommand {{ authorizedkeyscommand }}

- name: enable AuthorizedKeysCommandUser
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?AuthorizedKeysCommandUser '
    line: AuthorizedKeysCommandUser nobody


- name: enable sssd (systemd)
  ansible.builtin.systemd:
    name: sssd
    enabled: yes
    masked: no
  when: >-
    ansible_facts['service_mgr'] == "systemd"

- name: enable sssd (bsdinit)
  community.general.sysrc:
    name: sssd_enable
    state: present
    value: "YES"
  when: >-
    ansible_facts['service_mgr'] == "bsdinit"

- name: restart sssd (systemd)
  ansible.builtin.systemd:
    name: sssd
    state: restarted
    daemon_reload: yes
  when: >-
    ansible_facts['service_mgr'] == "systemd"

- name: restart oddjobd
  ansible.builtin.systemd:
    name: oddjobd
    state: restarted
    daemon_reload: yes
  when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Rocky"

- name: restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted
    daemon_reload: yes
  when: ansible_facts['os_family'] == "Debian"

- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    daemon_reload: yes
  when: >-
    ansible_facts['os_family'] == "RedHat" or
    ansible_facts['os_family'] == "Rocky"

- name: enable mkhomedir for Debian
  shell: |
    pam-auth-update --enable mkhomedir --force
  when: ansible_facts['os_family'] == "Debian"

- name: enable mkhomedir for RedHat
  ansible.builtin.shell: |
    authselect select sssd with-sudo with-mkhomedir --force
    systemctl enable --now oddjobd.service
  when: >-
    ansible_facts['os_family'] == "RedHat" or
    ansible_facts['os_family'] == "Rocky"


- name: add sss for nsswitch group
  ansible.builtin.replace:
    path: /etc/nsswitch.conf
    regexp: '^group: compat'
    replace: 'group: files sss'
  when: >-
    ansible_facts['service_mgr'] == "bsdinit"

- name: add sss for nsswitch passwd
  ansible.builtin.replace:
    path: /etc/nsswitch.conf
    regexp: '^passwd: compat'
    replace: 'passwd: files sss'
  when: >-
    ansible_facts['service_mgr'] == "bsdinit"

- name: add sss in nsswitch sudo
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    line: 'sudoers: files sss'
  when: >-
    ansible_facts['service_mgr'] == "bsdinit"

- name: copy ldap.conf
  template:
    src: freebsd-ldap.conf
    dest: /usr/local/etc/openldap/ldap.conf
    mode: '0644'
  when: >-
    ansible_facts['service_mgr'] == "bsdinit"

- name: copy sshd for pam
  template:
    src: freebsd-etc-pam.d-sshd
    dest: /etc/pam.d/sshd
    mode: '0644'
  when: >-
    ansible_facts['service_mgr'] == "bsdinit"

- name: copy system for pam
  template:
    src: freebsd-etc-pam.d-system
    dest: /etc/pam.d/system
    mode: '0644'
  when: >-
    ansible_facts['service_mgr'] == "bsdinit"

- name: restart sshd (bsdinit)
  ansible.builtin.service:
    name: sshd
    state: restarted
  when: >-
    ansible_facts['service_mgr'] == "bsdinit"

- name: restart sssd (bsdinit)
  ansible.builtin.service:
    name: sssd
    state: restarted
  when: >-
    ansible_facts['service_mgr'] == "bsdinit"



