- name: setup couchdb3
  hosts: couchdb

  tasks:
  - name: install couchdb3
    ansible.builtin.package:
      name:
      - couchdb3
      - ca_root_nss
      state: present
  
  - name: enable couchdb3
    community.general.sysrc:
      name: "couchdb3_enable"
      value: "YES"

  - name: upload local.ini
    ansible.builtin.copy:
      src:  local.ini
      dest: /usr/local/etc/couchdb3/
      owner: couchdb
      group: couchdb
      mode: '0600'
  
  - name: upload server cert
    ansible.builtin.copy:
      src:  couchdb.crt
      dest: /usr/local/etc/ssl/
      owner: couchdb
      group: couchdb
      mode: '0600'
  
  - name: upload server key
    ansible.builtin.copy:
      src:  couchdb.key
      dest: /usr/local/etc/ssl/
      owner: couchdb
      group: couchdb
      mode: '0600'

  - name: start couchdb3
    ansible.builtin.service:
      name:  couchdb3
      state: restarted

